# Generated by Django 4.1.5 on 2023-01-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0002_post_author_post_contact_post_date_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
