# Generated by Django 4.1.5 on 2023-01-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0004_intern_company_intern_name_intern_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='course/image'),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
